services:
  backend:
    image: ghcr.io/organization-wedding/parasempre-backend:prod-latest
    container_name: parasempre-prod-backend
    env_file: .env
    restart: unless-stopped
    networks:
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.parasempre-prod-backend.rule=Host(`api.nosparasempre.com.br`)"
      - "traefik.http.routers.parasempre-prod-backend.entrypoints=websecure"
      - "traefik.http.routers.parasempre-prod-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.parasempre-prod-backend.loadbalancer.server.port=8080"

  frontend:
    image: ghcr.io/organization-wedding/parasempre-frontend:prod-latest
    container_name: parasempre-prod-frontend
    env_file: .env
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - traefik-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.parasempre-prod-frontend.rule=Host(`nosparasempre.com.br`) || Host(`www.nosparasempre.com.br`)"
      - "traefik.http.routers.parasempre-prod-frontend.entrypoints=websecure"
      - "traefik.http.routers.parasempre-prod-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.parasempre-prod-frontend.loadbalancer.server.port=3000"

networks:
  traefik-web:
    external: true
